SEED: 42

dataset:
  train_hr_dir: "data\\processed\\DIV2K\\cubic_X4_pixels96_stride48\\train\\hr" #"data\\raw\\DIV2K\\HR\\train" # 
  train_lr_dir: "data\\processed\\DIV2K\\cubic_X4_pixels96_stride48\\train\\lr" #""
  valid_hr_dir: "data\\raw\\Set5"
  crop_size: 96
  stride: 48
  upscale_factor: 4
  interpolation: "cubic"
  
train:
  model: "SRGAN"
  benchmark: "v1"  # Custom tag for result tracking
  SRCNN: 
    resume: ""  # Path to pre-trained model models/srcnn_x2-T91-7d6e0623.pth.tar
    parameters:
      f1: 9
      f2: 1
      f3: 5
      n1: 64
      n2: 32
    epochs: 2
    batch_size: 64
    model_momentum: 0.9
  SRGAN:
    resume: "SRGAN_v1_20250723_005214"  # Path to pre-trained model
    parameters:
      learning_rate_generator: 1e-4
      learning_rate_discriminator: 1e-4
      b1: 0.9
      b2: 0.999
      lambda_adversarial: 1e-3
      lambda_content: 1e-3
    epochs: 10
    batch_size: 64

evaluate:
  lr_dir: "data/Set5/GTmod12"
  sr_dir: "results/test/SRCNN"
  hr_dir: "data/Set5/GTmod12"
  model_path: "results/pretrained_models/srcnn_x2-T91-7d6e0623.pth.tar"
